name: PR Quality Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - run: npm ci
      - name: Run ESLint on changed files
        run: |
          CHANGED="$(git diff --name-only --diff-filter=ACMR "${{ github.event.pull_request.base.sha }}" "${{ github.sha }}" | grep -E '\.(ts|tsx|js|jsx)$' || true)"
          [ -z "$CHANGED" ] && echo "No JS/TS changes." && exit 0
          echo "$CHANGED" | xargs -r -I {} npx eslint {}

  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - run: npm ci
      - name: Run Prettier check on changed files
        run: |
          CHANGED="$(git diff --name-only --diff-filter=ACMR "${{ github.event.pull_request.base.sha }}" "${{ github.sha }}" | grep -E '\.(ts|tsx|js|jsx)$' || true)"
          [ -z "$CHANGED" ] && echo "No JS/TS changes." && exit 0
          echo "$CHANGED" | xargs -r -I {} npx prettier --check {}